from .cl_tagger_v2 import (
    NODE_CLASS_MAPPINGS as CL_TAGGER_NODE_CLASS_MAPPINGS,
)
from .cl_tagger_v2 import (
    NODE_DISPLAY_NAME_MAPPINGS as CL_TAGGER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .random_text_picker import (
    NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS,
)
from .random_text_picker import (
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **PROMPT_NODE_CLASS_MAPPINGS,
    **CL_TAGGER_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
    **CL_TAGGER_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
